[package]
name = "databow"
description = "A command-line tool for querying databases via ADBC"
version = "0.1.2"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/columnar-tech/databow"
keywords = ["database", "sql", "adbc"]
categories = ["command-line-utilities", "database"]
include = ["/src", "/themes", "build.rs", "LICENSE", "README.md"]

[dependencies]
adbc_core = "0.24.0"
adbc_driver_manager = "0.24.0"
arrow = { version = "59.3.0", features = ["chrono-tz"] }
arrow-array = "59.3.0"
arrow-cast = "59.3.0"
arrow-schema = "59.3.0"
clap = { version = "4.6.7", features = ["derive"] }
comfy-table = "8.0.1"
nu-ansi-term = "0.50.3"
reedline = "0.52.0"
syntect = "5.3.0"
terminal-colorsaurus = "1.0.3"

[dev-dependencies]
arrow-buffer = "59.3.0"
tempfile = "3.27.0"
